name: BungeePortals
version: ${project.version}
description: Create portals of any shape or size with WorldEdit, for BungeeCord.
author: TheQurekPL
main: pl.qurek.bungeeportals.BungeePortals
softdepend: [WorldEdit]
api-version: 1.17

commands:
    BPortals:
        description: Do cool stuff.
permissions:
    BungeePortals.command.BPortals:
        description: Allowed to access the command /BPortals.
        default: op
    BungeePortals.portal.*:
        description: Access to all portals.
        default: true